name: null
favicon: null
layout_spectrum: 0.24744
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23241f'
    - '#585340'
    - '#817c5c'
    - '#a59a77'
    - '#e3c193'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 386fa786-2352-435b-98ed-01a660206a8a
    url: null
